/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChannelChannelIdRouteRouteImport } from './routes/channel.$channelId.route'
import { Route as ChannelChannelIdIndexRouteImport } from './routes/channel.$channelId.index'
import { Route as ChannelChannelIdVideosRouteImport } from './routes/channel.$channelId.videos'
import { Route as ChannelChannelIdPlaylistsRouteImport } from './routes/channel.$channelId.playlists'

const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelChannelIdRouteRoute = ChannelChannelIdRouteRouteImport.update({
  id: '/channel/$channelId',
  path: '/channel/$channelId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelChannelIdIndexRoute = ChannelChannelIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChannelChannelIdRouteRoute,
} as any)
const ChannelChannelIdVideosRoute = ChannelChannelIdVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => ChannelChannelIdRouteRoute,
} as any)
const ChannelChannelIdPlaylistsRoute =
  ChannelChannelIdPlaylistsRouteImport.update({
    id: '/playlists',
    path: '/playlists',
    getParentRoute: () => ChannelChannelIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/watch': typeof WatchRoute
  '/channel/$channelId': typeof ChannelChannelIdRouteRouteWithChildren
  '/channel/$channelId/playlists': typeof ChannelChannelIdPlaylistsRoute
  '/channel/$channelId/videos': typeof ChannelChannelIdVideosRoute
  '/channel/$channelId/': typeof ChannelChannelIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/watch': typeof WatchRoute
  '/channel/$channelId/playlists': typeof ChannelChannelIdPlaylistsRoute
  '/channel/$channelId/videos': typeof ChannelChannelIdVideosRoute
  '/channel/$channelId': typeof ChannelChannelIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/watch': typeof WatchRoute
  '/channel/$channelId': typeof ChannelChannelIdRouteRouteWithChildren
  '/channel/$channelId/playlists': typeof ChannelChannelIdPlaylistsRoute
  '/channel/$channelId/videos': typeof ChannelChannelIdVideosRoute
  '/channel/$channelId/': typeof ChannelChannelIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/watch'
    | '/channel/$channelId'
    | '/channel/$channelId/playlists'
    | '/channel/$channelId/videos'
    | '/channel/$channelId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/watch'
    | '/channel/$channelId/playlists'
    | '/channel/$channelId/videos'
    | '/channel/$channelId'
  id:
    | '__root__'
    | '/'
    | '/watch'
    | '/channel/$channelId'
    | '/channel/$channelId/playlists'
    | '/channel/$channelId/videos'
    | '/channel/$channelId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WatchRoute: typeof WatchRoute
  ChannelChannelIdRouteRoute: typeof ChannelChannelIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel/$channelId': {
      id: '/channel/$channelId'
      path: '/channel/$channelId'
      fullPath: '/channel/$channelId'
      preLoaderRoute: typeof ChannelChannelIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel/$channelId/': {
      id: '/channel/$channelId/'
      path: '/'
      fullPath: '/channel/$channelId/'
      preLoaderRoute: typeof ChannelChannelIdIndexRouteImport
      parentRoute: typeof ChannelChannelIdRouteRoute
    }
    '/channel/$channelId/videos': {
      id: '/channel/$channelId/videos'
      path: '/videos'
      fullPath: '/channel/$channelId/videos'
      preLoaderRoute: typeof ChannelChannelIdVideosRouteImport
      parentRoute: typeof ChannelChannelIdRouteRoute
    }
    '/channel/$channelId/playlists': {
      id: '/channel/$channelId/playlists'
      path: '/playlists'
      fullPath: '/channel/$channelId/playlists'
      preLoaderRoute: typeof ChannelChannelIdPlaylistsRouteImport
      parentRoute: typeof ChannelChannelIdRouteRoute
    }
  }
}

interface ChannelChannelIdRouteRouteChildren {
  ChannelChannelIdPlaylistsRoute: typeof ChannelChannelIdPlaylistsRoute
  ChannelChannelIdVideosRoute: typeof ChannelChannelIdVideosRoute
  ChannelChannelIdIndexRoute: typeof ChannelChannelIdIndexRoute
}

const ChannelChannelIdRouteRouteChildren: ChannelChannelIdRouteRouteChildren = {
  ChannelChannelIdPlaylistsRoute: ChannelChannelIdPlaylistsRoute,
  ChannelChannelIdVideosRoute: ChannelChannelIdVideosRoute,
  ChannelChannelIdIndexRoute: ChannelChannelIdIndexRoute,
}

const ChannelChannelIdRouteRouteWithChildren =
  ChannelChannelIdRouteRoute._addFileChildren(
    ChannelChannelIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WatchRoute: WatchRoute,
  ChannelChannelIdRouteRoute: ChannelChannelIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
